language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# environment
env:
  FLASK_ENV=testing
  DEV_SQLALCHEMY_DATABASE_URI=postgresql://postgres@localhost/resourceidea_test?sslmode=disable
  SECRET_KEY=kmJnJ8NQDOjn+FrLappG9A4EfL
services:
  - postgresql
before_script:
  - psql -c 'create database resourceidea_test;' -U postgres
  - psql -c 'create extension if not exists "uuid-ossp";'
# command to run tests
script:
  - pytest -p no:warnings --cov-report=term-missing --cov=app

after_success:
  - coveralls
