language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# environment
env:
  FLASK_ENV=testing
services:
  - postgresql
before_script:
  - psql -c 'create database resourceidea_test;' -U postgres
  - psql -U postgres resourceidea_test -c 'create extension if not exists "uuid-ossp";'
# command to run tests
script:
  - pytest -p no:warnings --cov-report=term-missing --cov=app

after_success:
  - coveralls
