language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest -p no:warnings --cov-report=term-missing --cov=app

after-success:
  - coveralls
