language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# environment
env:
  FLASK_ENV=testing
  TEST_SQLALCHEMY_DATABASE_URI=postgresql://riuser@localhost/resourceidea_test?sslmode=disable
  SECRET_KEY=kmJnJ8NQDOjn+FrLappG9A4EfL
services:
  - postgresql
# command to run tests
script:
  - pytest -p no:warnings --cov-report=term-missing --cov=app

after-success:
  - coveralls
