language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# environment
env:
  FLASK_ENV=testing
  DEV_SQLALCHEMY_DATABASE_URI=postgresql://postgres@localhost/resourceidea_test?sslmode=disable
  SECRET_KEY=kmJnJ8NQDOjn+FrLappG9A4EfL
  AWS_SES_SENDER=support@resourceidea.com
  AWS_REGION=us-west-2
  AWS_ACCESS_KEY_ID= AKIARXPW47W7V2B7KEJZ
  AWS_SECRET_ACCESS_KEY= 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
services:
  - postgresql
before_script:
  - psql -c 'create database resourceidea_test;' -U postgres
  - psql -U postgres resourceidea_test -c 'create extension if not exists "uuid-ossp";'
# command to run tests
script:
  - pytest -p no:warnings --cov-report=term-missing --cov=app

after_success:
  - coveralls
