version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-node-browsers
        environment:
          FLASK_ENV: testing
          DEV_SQLALCHEMY_DATABASE_URI: postgresql://riuser@localhost/resourceidea_test?sslmode=disable
          SECRET_KEY: kmJnJ8NQDOjn+FrLappG9A4EfL
      - image: circleci/postgres:9.6.12
        environment:
          POSTGRES_USER: riuser
          POSTGRES_DB: resourceidea_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: PostgreSQL Client
          command: |
            sudo apt install postgresql-client
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: PostgreSQL Extensions
          command: |
            sudo psql -h localhost -p 5432 -c 'create extension if not exists "uuid-ossp";'
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv*,migrations* --statistics
            pytest -p no:warnings --cov=app
