version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-node-browsers
        environment:
          FLASK_ENV: testing
          DEV_SQLALCHEMY_DATABASE_URI: postgresql://riuser@localhost/resourceidea_test?sslmode=disable
          SECRET_KEY: kmJnJ8NQDOjn+FrLappG9A4EfL
      - image: circleci/postgres:9.6.12
        environment:
          POSTGRES_USER: riuser
          POSTGRES_DB: resourceidea_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: postgres extensions
          command: |
            psql -U riuser resourceidea_test -c 'create extension if not exists "uuid-ossp";'
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv*,migrations* --statistics
            pytest -p no:warnings --cov=app
