"""empty message

Revision ID: 0e535efba4a9
Revises: 08f17019b5a2
Create Date: 2019-01-29 10:48:28.186802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e535efba4a9'
down_revision = '08f17019b5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('user_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'user_account', ['user_account_id'], ['id'])
    op.drop_constraint('job_ibfk_5', 'job', type_='foreignkey')
    op.drop_constraint('job_ibfk_4', 'job', type_='foreignkey')
    op.add_column('user_account', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_account', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.drop_column('user_account', 'company_id')
    op.create_foreign_key('job_ibfk_4', 'job', 'resource', ['manager_id'], ['id'])
    op.create_foreign_key('job_ibfk_5', 'job', 'resource', ['partner_id'], ['id'])
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'user_account_id')
    # ### end Alembic commands ###
