"""Removing manager and partner relation from job entity

Revision ID: 2612329c102a
Revises: 5cbce769471e
Create Date: 2019-01-29 14:09:50.952918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2612329c102a'
down_revision = '5cbce769471e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_ibfk_5', 'job', type_='foreignkey')
    op.drop_constraint('job_ibfk_4', 'job', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('job_ibfk_4', 'job', 'resource', ['manager_id'], ['id'])
    op.create_foreign_key('job_ibfk_5', 'job', 'resource', ['partner_id'], ['id'])
    # ### end Alembic commands ###
