"""empty message

Revision ID: 2c6d92caccf7
Revises: 0e535efba4a9
Create Date: 2019-01-29 10:51:46.814672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6d92caccf7'
down_revision = '0e535efba4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'job', 'resource', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'job', 'resource', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='foreignkey')
    # ### end Alembic commands ###
