"""empty message

Revision ID: 5cbce769471e
Revises: 2c6d92caccf7
Create Date: 2019-01-29 12:32:58.799461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cbce769471e'
down_revision = '2c6d92caccf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    op.drop_column('employee', 'resource_id')
    op.add_column('resource', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource', 'employee', ['employee_id'], ['id'])
    op.drop_constraint('user_account_ibfk_1', 'user_account', type_='foreignkey')
    op.drop_column('user_account', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_account_ibfk_1', 'user_account', 'employee', ['employee_id'], ['id'])
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'employee_id')
    op.add_column('employee', sa.Column('resource_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('employee_ibfk_1', 'employee', 'resource', ['resource_id'], ['id'])
    # ### end Alembic commands ###
